// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HomepageTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void homepageTest() {
    driver.get("http://localhost/386_web/");
    driver.manage().window().setSize(new Dimension(1167, 813));
    driver.findElement(By.cssSelector(".column:nth-child(2) .btn")).click();
    driver.findElement(By.cssSelector("tr:nth-child(4) .btn2")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Sami Tanquary");
    driver.findElement(By.id("email")).sendKeys("samitanquary@gmail.com");
    driver.findElement(By.id("phoneNumber")).sendKeys("4803135307");
    driver.findElement(By.id("dateStart")).click();
    driver.findElement(By.id("dateStart")).sendKeys("2021-12-21");
    driver.findElement(By.id("dateEnd")).click();
    driver.findElement(By.id("dateEnd")).click();
    driver.findElement(By.id("dateEnd")).sendKeys("2021-12-16");
    driver.findElement(By.cssSelector(".btn3")).click();
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.cssSelector(".column:nth-child(1) .btn")).click();
    driver.findElement(By.id("make")).click();
    driver.findElement(By.id("make")).sendKeys("Audi");
    driver.findElement(By.id("make")).click();
    driver.findElement(By.id("make")).sendKeys("GMC");
    driver.findElement(By.id("model")).sendKeys("Denali");
    driver.findElement(By.id("carYear")).sendKeys("2007");
    driver.findElement(By.id("mileage")).sendKeys("23748");
    driver.findElement(By.id("color")).sendKeys("grey");
    driver.findElement(By.id("color")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("button")).click();
  }
}
