// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LoginTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginTest() {
    // Test name: LoginTest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://127.0.0.1:8887/");
    // 2 | setWindowSize | 1129x813 | 
    driver.manage().window().setSize(new Dimension(1129, 813));
    // 3 | click | linkText=Sign-in | 
    driver.findElement(By.linkText("Sign-in")).click();
    // 4 | click | name=uname | 
    driver.findElement(By.name("uname")).click();
    // 5 | type | name=uname | sami780
    driver.findElement(By.name("uname")).sendKeys("sami780");
    // 6 | click | name=pass | 
    driver.findElement(By.name("pass")).click();
    // 7 | type | name=pass | 123456
    driver.findElement(By.name("pass")).sendKeys("123456");
    // 8 | click | css=button | 
    driver.findElement(By.cssSelector("button")).click();
  }
}
