// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegisterCarTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registerCarTest() {
    // Test name: RegisterCarTest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://127.0.0.1:8887/");
    // 2 | setWindowSize | 1129x813 | 
    driver.manage().window().setSize(new Dimension(1129, 813));
    // 3 | click | linkText=Rent out your car! | 
    driver.findElement(By.linkText("Rent out your car!")).click();
    // 4 | click | id=make | 
    driver.findElement(By.id("make")).click();
    // 5 | type | id=make | jeep
    driver.findElement(By.id("make")).sendKeys("jeep");
    // 6 | click | id=model | 
    driver.findElement(By.id("model")).click();
    // 7 | doubleClick | id=model | 
    {
      WebElement element = driver.findElement(By.id("model"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 8 | type | id=model | cherokee
    driver.findElement(By.id("model")).sendKeys("cherokee");
    // 9 | click | id=carYear | 
    driver.findElement(By.id("carYear")).click();
    // 10 | type | id=carYear | 2012
    driver.findElement(By.id("carYear")).sendKeys("2012");
    // 11 | click | id=mileage | 
    driver.findElement(By.id("mileage")).click();
    // 12 | doubleClick | id=mileage | 
    {
      WebElement element = driver.findElement(By.id("mileage"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 13 | type | id=mileage | 10000
    driver.findElement(By.id("mileage")).sendKeys("10000");
    // 14 | click | id=color | 
    driver.findElement(By.id("color")).click();
    // 15 | type | id=color | white
    driver.findElement(By.id("color")).sendKeys("white");
    // 16 | click | css=input:nth-child(1) | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
  }
}
